### ISSUE TITLE
Undefined method 'newQuery'. The method name must start with either findBy or findOneBy!

### ISSUE THREAD

**Issue by kfeng0806** [laravel-doctrine/scout#13]
I have upgraded Laravel scout to the latest ^3.0 version, then i getting this error during search, but seems it works fine with Laravel scout ^2.0

```
local.ERROR: Undefined method 'newQuery'. The method name must start with either findBy or findOneBy! {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'newQuery'. The method name must start with either findBy or findOneBy! at /vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:226)
[stacktrace]
#0 /vendor/laravel/scout/src/Engines/AlgoliaEngine.php(173): Doctrine\\ORM\\EntityRepository->__call('newQuery', Array)
#1 /vendor/laravel/scout/src/Builder.php(221): Laravel\\Scout\\Engines\\AlgoliaEngine->map(Array, Object(App\\Repositories\\PostRepository))
#2 /app/Http/Controllers/Api/SearchController.php(60): Laravel\\Scout\\Builder->paginate(24)
#3 [internal function]: App\\Http\\Controllers\\Api\\SearchController->index(Object(App\\Http\\Requests\\SearchRequest))
```

**Comment by patrickbrouwers** [comment]
Assuming Scout has added a new method in 3.0 that is not present yet , feel free to PR the fix.

**Comment by xtrasmal** [comment]
@patrickbrouwers 
I have the same problem, but with the tntengine. 
I am not sure how to fix this and what it actually means or else I would have made a PR

**Comment by xtrasmal** [comment]
@patrickbrouwers after updating to L6 this weekend I looked at the problem again and noticed that the only thing needed was to add the following to the SearchRepository. 

```php
public function newQuery()
{
	return $this;
}
```
After that, all versions should be compatible.

**Comment by eigan** [comment]
Seems to be fixed in an earlier commit: bceb0c6b58e4d3d6078576065738af793f2c8dd4
